<script src="{{url('stack_admin')}}/app-assets/vendors/js/tables/datatable/datatables.min.js"></script>
<script src="{{url('stack_admin')}}/app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js"></script>
<script src="{{url('stack_admin')}}/app-assets/vendors/js/tables/datatable/buttons.bootstrap4.min.js"></script>
<script src="{{url('stack_admin')}}/app-assets/vendors/js/tables/jszip.min.js"></script>
<script src="{{url('stack_admin')}}/app-assets/vendors/js/tables/pdfmake.min.js"></script>
<script src="{{url('stack_admin')}}/app-assets/vendors/js/tables/vfs_fonts.js"></script>
<script src="{{url('stack_admin')}}/app-assets/vendors/js/tables/buttons.html5.min.js"></script>
<script src="{{url('stack_admin')}}/app-assets/vendors/js/tables/buttons.print.min.js"></script>
<script src="{{url('stack_admin')}}/app-assets/vendors/js/tables/buttons.colVis.min.js"></script>
<script src="{{url('stack_admin')}}/app-assets/js/scripts/tables/datatables-extensions/datatable-button/datatable-button-basic.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>